import torch
import torch.nn as nn
import torch.nn.init as init

class ChurnModule(nn.Module):
    def __init__(self):
        super(ChurnModule, self).__init__()
        self.layer1 = nn.Linear(11, 30)
        self.actv1 = nn.Hardswish()
        self.bn1 = nn.BatchNorm1d(30)
        self.layer2 = nn.Linear(30, 60)
        self.actv2 = nn.ReLU()
        self.bn2 = nn.BatchNorm1d(60)
        self.layer3 = nn.Linear(60, 90)
        self.actv3 = nn.Hardswish()
        self.bn3 = nn.BatchNorm1d(90)
        self.layer4 = nn.Linear(90, 64)
        self.bn4 = nn.BatchNorm1d(64)
        self.layer5 = nn.Linear(64, 256)
        self.actv4 = nn.Sigmoid()
        self.bn5 = nn.BatchNorm1d(256)
        self.layer6 = nn.Linear(256, 64)
        self.actv5 = nn.Hardswish()
        self.bn6 = nn.BatchNorm1d(64)
        self.layer7 = nn.Linear(64, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.layer8 = nn.Linear(256, 512)
        self.actv6 = nn.ReLU()
        self.bn8 = nn.BatchNorm1d(512)
        self.layer9 = nn.Linear(512, 128)
        self.actv7 = nn.Hardswish()
        self.bn9 = nn.BatchNorm1d(128)
        self.layer10 = nn.Linear(128, 1)
        self.final = nn.Sigmoid()
        
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.actv1(x)
        x = self.bn1(x)
        x = self.layer2(x)
        x = self.actv2(x)
        x = self.bn2(x)
        x = self.layer3(x)
        x = self.actv3(x)
        x = self.bn3(x)
        x = self.layer4(x)
        x = self.bn4(x)
        x = self.layer5(x)
        x = self.actv4(x)
        x = self.bn5(x)
        x = self.layer6(x)
        x = self.actv5(x)
        x = self.bn6(x)
        x = self.layer7(x)
        x = self.bn7(x)
        x = self.layer8(x)
        x = self.actv6(x)
        x = self.bn8(x)
        x = self.layer9(x)
        x = self.actv7(x)
        x = self.bn9(x)
        x = self.layer10(x)
        score = self.final(x)
        return score
    